### ISSUE TITLE
How to create a modrinth server.

### ISSUE THREAD

**Issue by ConnorAtmos** [nothub/mrpack-install#47]
Ok. I want to create a server for this modpack: https://modrinth.com/modpack/the-amazing-world-of-buddy/changelog

I run:
mrpack-install JK8HDnay

It creates a .mrpack in ~/mc directory but it doesn't give me anywhere as to the location of the server itself

```
~$ mrpack-install JK8HDnay
Downloading mrpack file from https://cdn.modrinth.com/data/JK8HDnay/versions/t65SnhrN/The%20Amazing%20World%20of%20Buddy%203.1.0.mrpack
Processing mrpack file mc/The Amazing World of Buddy 3.1.0.mrpack
Installing: The Amazing World of Buddy
Flavor dependencies: {Minecraft:1.20.1 Fabric: Quilt: Forge:47.2.17}
Server file not present, downloading...
(Point --server-dir and --server-file flags to an existing server file to skip this step.)
Please acquire the required forge server file (47.2.17) manually to continue: https://files.minecraftforge.net/net/minecraftforge/forge/index_1.20.1.html
2024/05/16 18:14:30 forge provider not implemented
```

Why does it create a .mrpack file when all I ask is server files? Like how can I go on forge and it has a .zip of server files for pretty much all modpacks, but that's not possible with mrpack-install? 

Is there a way to actually get the files for this so that all I have to do is cd into the minecraft server directory and do ./run.sh?

**Comment by nothub** [comment]
> Why does it create a .mrpack file when all I ask is server files?

The mrpack file is downloaded from the modrinth server.

> Like how can I go on forge and it has a .zip of server files for pretty much all modpacks, but that's not possible with mrpack-install?

I am not sure what your question is. I have never seen zip files for all modpacks on forge (the forge website?)

> Is there a way to actually get the files for this so that all I have to do is cd into the minecraft server directory and do ./run.sh?

Yes, the command you executed does exactly that.
If you read the log output your command invocation produced, you will find an information about downloading the forge server.
If you want the server to be installed automatically instead of having to manually download it, you can use the current [beta release](https://github.com/nothub/mrpack-install/releases/tag/v0.17.2-beta) of mrpack-install.
